# Generated by Django 3.2.5 on 2021-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=100)),
                ('thumb', models.ImageField(blank=True, default='', null=True, upload_to='thumbnail')),
            ],
        ),
    ]
